Gaussian Noise to Coupled Training
AtmosSci-DLESM/modulus-uw pull request #2
Opened 2024-11-26 22:58 UTC by zacespinosa

# Modulus Pull Request

## Description

Here I add the ability to apply gaussian noise to inputs and coupled variables during training of coupled models. This should improve the stability of coupled rollouts. As it's written, this is not a breaking change - i.e. this code can be merged and no changes to anyones configs are necessary (defaults to applying no noise). I have tested this for training coupled DLWP and DLOM models. Here are examples of the new variables to be added to data/module yaml: 

![Screenshot 2024-11-26 at 2 56 40 PM](https://github.com/user-attachments/assets/bddf411c-d3cd-4961-af7e-f5a5a8be8fcf)

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [ ] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is up to date with these changes.
- [ ] An [issue](https://github.com/NVIDIA/modulus/issues) is linked to this pull request.

## Dependencies

2024-11-26 23:02 UTC, yairchn approved these changes
LGTM

2024-11-28 03:36 UTC, nathanielcresswellclay commented on modulus/datapipes/healpix/coupledtimeseries_dataset.py
> +                inputs[:, :, i] += np.random.normal(
I recommend adding an additional random seed parameter. This way we have fully reproducible training.

2024-11-28 03:39 UTC, nathanielcresswellclay requested changes
Good implementation-- the change is happening in the right place. 

I think before merging, you should add support for setting the random seed of your gaussian noise. Pretty minor adjustment, but then we can maintain 100% reproducibility in training.

2024-12-16 23:39 UTC, nathanielcresswellclay approved these changes

2024-12-16 23:52 UTC, merged